language: python

python:
    - 3.6

before_install:
  - echo "START"

install:
  - pip install -r requirements.txt

script:
    - ./test.sh

# blacklist
branches:
  except:
    - legacy
    - dev

# whitelist
branches:
  only:
    - master
    - stable

notifications:
  email:
    - npiusdan@gmail.com
  on_success: change
  on_failure: always